### ISSUE TITLE
关于登录名的修改

### ISSUE THREAD

**Issue by Zlzzzupup** [bychen009/hao4k-auto-sign-in#1]
感谢大佬，在此基础上完成了hao4k的自动登陆签到。
但是有个小问题，希望能修改完善一下，能更好。
```python
    if 'PoplarChan' in test_resp.text:
        print('login!')
    else:
        return('login failed!')
```
代码38行中的‘Poplarchan’可以直接换成username，更直接方便大家，不需要每个人都单独修改用户名。幸好看了一下源码不然总是报错。谢谢了！

**Comment by bychen009** [comment]
感谢提醒，周末修改一下。
